version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysqlVolume:/var/lib/mysql
      - mysqlConfig:/etc/mysql

  app:
    build:
      context: .
    ports:
      - 8080:5000
    depends_on:
      - mysqldb

volumes:
  mysqlVolume:
  mysqlConfig:
